[workspace]
resolver = "2"
members = ["orrun"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.lints.rust]
warnings = "deny"

[workspace.dependencies]
engine = { path = "../Engine/engine" }
modular = { path = "../Modular/modular" }
glam = { version = "0.30", features = ["bytemuck"] }
thiserror = "2"
rand = "0.8"
rand_chacha = "0.3"
rustc-hash = "2"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
